# Generated by Django 5.0.7 on 2024-07-23 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='full_info',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='app.category'),
        ),
    ]
